---
- name: Install Apache
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Get FQDN of the node
  shell: hostname -f
  register: fqdn_result

- name: Create index.html file with FQDN
  copy:
    content: "Hello from {{ fqdn_result.stdout }} ({{ inventory_hostname }})"
    dest: /var/www/html/index.html
    mode: '0444'

- name: Ensure Apache is running and enabled
  service:
    name: apache2
    state: started
    enabled: yes
